# 
version: "3"
services:
  web:
    platform: linux/amd64
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
  app:
    platform: linux/amd64
    build: ./app
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html


  mysql:
    image: mysql:8.0.26
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf/my.cnf:/etc/mysql/conf.d/my.cnf
